% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Sep-2023 23:26:16
%  MATLAB version: 9.12.0.1884302 (R2022a)
% -------------------------------------------------------------------
saveVarsMat = load('WorkSapace.mat');

In = saveVarsMat.In; % <1x1 timeseries> unsupported class

clear saveVarsMat;
